service: myriapoda

provider:
  name: aws
  runtime: go1.x
  memorySize: 128

package:
 exclude:
   - ./**
 include:
   - ./target/x86_64-unknown-linux-musl/release/aws_api

functions:
  api:
    handler: target/x86_64-unknown-linux-musl/release/aws_api
    events:
      - http:
          path: welcome
          method: get
      - http:
          path: mirror
          method: post
      - http:
          path: conferences
          method: post
